=== johanenciso0311/MARCAS/proyectos-xml-main/XSl and XSD/Ejemplos /registro_temperatura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="nombre_incidencia">
    <xs:restriction base="xs:string">
        <xs:enumeration value="frio"/>
        <xs:enumeration value="nieve"/>
        <xs:enumeration value="lluvia"/>
        <xs:enumeration value="calor"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="severidad_incidencia">
    <xs:restriction base="xs:string">
        <xs:enumeration value="baja"/>
        <xs:enumeration value="media"/>
        <xs:enumeration value="alta"/>
    </xs:restriction>
</xs:simpleType>


    <xs:element name="registro_temperatura">
        <xs:complexType>
            <xs:sequence>            
                <xs:element name="provincia" type="xs:string"/>          
               
                <xs:element name="fecha" type="xs:date"/>         
               
                <xs:element name="temperatura_minima">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="-50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
               
                <xs:element name="temperatura_maxima">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:maxInclusive value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
               
                <xs:element name="incidencias">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="incidencia" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="nombre" type="nombre_incidencia"/>
                                    <xs:attribute name="severidad" type="severidad_incidencia"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>                                      
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== johanenciso0311/MARCAS/proyectos-xml-main/XSD and XML/temperatura/registro_temperatura.xml
<?xml version="1.0" encoding="UTF-8"?>
<registro_temperatura
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="registro_temperatura.xsd">
    <provincia>Madrid</provincia>
    <fecha>2004-03-11</fecha>
    <temperatura_minima>-5</temperatura_minima>
    <temperatura_maxima>4</temperatura_maxima>
    <incidencias>
        <incidencia nombre="frio" severidad="alta"/>
        <incidencia nombre="nieve" severidad="alta"/>
        <incidencia nombre="lluvia" severidad="media"/>
    </incidencias>
</registro_temperatura>
