=== johanenciso0311/MARCAS/proyectos-xml-main/XSD and XML/Ejemplo_factura/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="numero" type="xs:integer"/>
                
                <xs:element name="cliente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            
                            <xs:element name="CIF"> 
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="9"></xs:length>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="concepto" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="importe" type="xs:double"/>
                            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="impuesto">
                    <xs:complexType mixed="true">
                        <xs:attribute name="nombre" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="total_factura">
                    <xs:complexType>
                        <xs:attribute name="euros" type="xs:double"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>       
    </xs:element>
</xs:schema>

=== johanenciso0311/MARCAS/proyectos-xml-main/XSD and XML/Ejemplo_factura/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="factura.xsd">
    <numero>1</numero>
    <cliente>
        <nombre>johan</nombre>
        <CIF>V12345672</CIF>
    </cliente>
    <concepto>
        <descripcion>Imprenta</descripcion>
        <importe>1000</importe>
    </concepto>
    <concepto>
        <descripcion>Maquetacion</descripcion>
        <importe>500.50</importe>
    </concepto>
    <impuesto nombre = "IVA">PENDIENTE</impuesto>
    <total_factura euros="1500.50"/>
</factura>
